version: '3'

services:
  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx
    ports:
      - "8000:80"

  node-server:
    build: node-server/
    container_name: node-server
    ports:
      - "3000:3000"
